import type {
  Candidate,
  ChecklistTemplate,
  Job,
  TimelineEntry,
  User,
} from '@/types';

export const seedUsers: User[] = [
  { id: 'u_admin', name: 'Alex Morgan', email: 'alex@agency.com', role: 'Admin', active: true },
  { id: 'u_rec1', name: 'Priya Shah', email: 'priya@agency.com', role: 'Recruiter', active: true },
  { id: 'u_rec2', name: 'Daniel Kim', email: 'daniel@agency.com', role: 'Recruiter', active: true },
  { id: 'u_hm', name: 'Sarah Chen', email: 'sarah@agency.com', role: 'HiringManager', active: true },
];

export const seedJobs: Job[] = [
  {
    id: 'j_1',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    location: 'Remote — EU',
    employmentType: 'Full-time',
    description:
      'We are looking for a Senior Frontend Engineer with deep experience in React, TypeScript, and modern web platforms. You will own complex user-facing features end-to-end and collaborate closely with design and backend teams.',
    status: 'Open',
    assignedRecruiterIds: ['u_rec1'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'j_2',
    title: 'Product Designer',
    department: 'Design',
    location: 'London, UK',
    employmentType: 'Full-time',
    description:
      'Join our design team to craft intuitive product experiences. You should have a strong portfolio demonstrating end-to-end design ownership.',
    status: 'Open',
    assignedRecruiterIds: ['u_rec2', 'u_rec1'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'j_3',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Berlin, DE',
    employmentType: 'Contract',
    description:
      'Help us scale our infrastructure on AWS. Expertise in Kubernetes, Terraform, and CI/CD pipelines required.',
    status: 'Open',
    assignedRecruiterIds: ['u_rec2'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];

export const seedCandidates: Candidate[] = [
  {
    id: 'c_1',
    jobId: 'j_1',
    fullName: 'Emma Wilson',
    email: 'emma.wilson@example.com',
    phone: '+44 20 7123 4567',
    resumeFileName: 'emma_wilson_cv.pdf',
    tags: ['React', 'TypeScript', 'Senior'],
    stage: 'Interview',
    assignedRecruiterId: 'u_rec1',
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    source: 'CareersPage',
  },
  {
    id: 'c_2',
    jobId: 'j_1',
    fullName: 'James Patel',
    email: 'james.patel@example.com',
    phone: '+1 415 555 0199',
    resumeFileName: 'james_patel_resume.pdf',
    tags: ['Frontend', 'Vue'],
    stage: 'Screened',
    assignedRecruiterId: 'u_rec1',
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    source: 'CareersPage',
  },
  {
    id: 'c_3',
    jobId: 'j_2',
    fullName: 'Sofia Rossi',
    email: 'sofia.rossi@example.com',
    phone: '+39 02 1234 5678',
    resumeFileName: 'sofia_rossi_portfolio.pdf',
    tags: ['UX', 'Figma'],
    stage: 'Offer',
    assignedRecruiterId: 'u_rec2',
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    source: 'Internal',
  },
  {
    id: 'c_4',
    jobId: 'j_3',
    fullName: 'Marcus Schmidt',
    email: 'marcus@example.com',
    phone: '+49 30 1234 5678',
    resumeFileName: 'marcus_schmidt.pdf',
    tags: ['AWS', 'Kubernetes', 'Referral'],
    stage: 'Referral',
    assignedRecruiterId: 'u_rec2',
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    source: 'Internal',
  },
  {
    id: 'c_5',
    jobId: 'j_1',
    fullName: 'Lina Hassan',
    email: 'lina.hassan@example.com',
    phone: '+971 50 123 4567',
    resumeFileName: 'lina_hassan.pdf',
    tags: ['React', 'Mid'],
    stage: 'Applied',
    assignedRecruiterId: null,
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    source: 'CareersPage',
  },
  {
    id: 'c_6',
    jobId: 'j_2',
    fullName: 'Tom Becker',
    email: 'tom.becker@example.com',
    phone: '+44 7700 900123',
    resumeFileName: 'tom_becker_cv.pdf',
    tags: ['Product Design'],
    stage: 'Onboarding',
    assignedRecruiterId: 'u_rec1',
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    source: 'Internal',
  },
];

export const seedTimeline: TimelineEntry[] = [
  {
    id: 't_1',
    candidateId: 'c_1',
    type: 'system',
    authorId: null,
    authorName: 'System',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    content: 'Application received via Careers Page.',
  },
  {
    id: 't_2',
    candidateId: 'c_1',
    type: 'stage_change',
    authorId: 'u_rec1',
    authorName: 'Priya Shah',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    content: 'Moved candidate forward after CV review.',
    fromStage: 'Applied',
    toStage: 'Screened',
  },
  {
    id: 't_3',
    candidateId: 'c_1',
    type: 'note',
    authorId: 'u_rec1',
    authorName: 'Priya Shah',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    content: 'Strong React/TS portfolio. Recommending technical interview.',
  },
  {
    id: 't_4',
    candidateId: 'c_1',
    type: 'email',
    authorId: 'u_rec1',
    authorName: 'Priya Shah',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    subject: 'Interview invitation — Senior Frontend Engineer',
    content:
      'Hi Emma,\n\nThanks for your application. We would love to invite you to a technical interview next week. Please let me know your availability.\n\nBest,\nPriya',
  },
];

export const seedChecklistTemplates: ChecklistTemplate[] = [
  {
    id: 'tpl_onboard',
    name: 'Standard Onboarding',
    stage: 'Onboarding',
    items: [
      { id: 'oi_1', label: 'Send welcome email & start date confirmation', requiresForm: false },
      { id: 'oi_2', label: 'Collect signed offer letter', requiresForm: true, formTemplate: 'Offer letter acceptance — name, signature, start date' },
      { id: 'oi_3', label: 'Collect tax & bank details form', requiresForm: true, formTemplate: 'Bank: account number, sort code. Tax: TIN, jurisdiction' },
      { id: 'oi_4', label: 'Provision IT accounts & equipment', requiresForm: false },
      { id: 'oi_5', label: 'Schedule day-1 orientation', requiresForm: false },
    ],
  },
  {
    id: 'tpl_bgcheck',
    name: 'Standard Background Check',
    stage: 'BackgroundCheck',
    items: [
      { id: 'bi_1', label: 'Identity verification (passport / national ID)', requiresForm: true, formTemplate: 'Document type, document number, expiry date' },
      { id: 'bi_2', label: 'Right-to-work confirmation', requiresForm: true, formTemplate: 'Visa / work permit details, expiry date' },
      { id: 'bi_3', label: 'Employment history verification (last 5 years)', requiresForm: false },
      { id: 'bi_4', label: 'Reference checks (minimum 2)', requiresForm: true, formTemplate: 'Referee 1 name, email, relationship. Referee 2 name, email, relationship.' },
      { id: 'bi_5', label: 'Criminal record check', requiresForm: false },
    ],
  },
];
